title: SimplyRETS documentation
theme: minima
author: SimplyRETS
email: support@simplyrets.com

twitter_username: SimplyRETS
github_username:  SimplyRETS
description: SimplyRETS API and WordPress plugin documentation. The easiest way to build real estate websites with data from your MLS.

collections:
  topics:
    output: true
    permalink: /topics/:title
