title: SimplyRETS documentation
theme: minima
# google_analytics: TODO
description: |
  SimplyRETS API and WordPress plugin documentation. The easiest way
  to build real estate websites with data from your MLS.
