title: SimplyRETS documentation
theme: minima
google_analytics: UA-58147010-1

twitter_username: SimplyRETS
github_username:  SimplyRETS
googleplus_username: +SimplyRETSInc
description: SimplyRETS API and WordPress plugin documentation. The easiest way to build real estate websites with data from your MLS.

collections:
  topics:
    output: true
    permalink: /topics/:title
